Relay.Web/Controllers/Safety/v2/SafetyArchiveV2Controller.cs
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using MomentumPlus.Relay.Constants;
using MvcPaging;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class SafetyArchiveV2Controller : BaseController
    {
        //IOC
        public SafetyArchiveV2Controller(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }


        public ActionResult Index(int? page, int? pageSize)
        {
            var model = Services.SafetyStatV2Service.PopulateArchivedSafetyMessagesViewModel().ToPagedList(page - 1 ?? 0, pageSize ?? NumericConstants.Paginator.PaginatorPageSize);

            return View("~/Views/Safety/v2/Archive/Index.cshtml", model);
        }


    }
}

Relay.Web/Controllers/Safety/v2/SafetyCriticalControlsV2Controller.cs
using System;
using MomentumPlus.Relay.Models;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using System.Net;
using System.Collections.Generic;

namespace MomentumPlus.Relay.Web.Controllers.Safety
{
    public class SafetyCriticalControlsV2Controller : BaseController
    {
        //IOC
        public SafetyCriticalControlsV2Controller(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork){}

        [HttpPost]
        public ActionResult GetCriticalControlsForMajorHazard(Guid majorHazardId)
        {
            if (majorHazardId != Guid.Empty)
            {
                IEnumerable<SelectListItem> criticalContrils = Services.CriticalControlV2Service.GetCriticalControlsList(majorHazardId);
                return Json(criticalContrils);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult GetCriticalControlInfo(Guid criticalControlId)
        {
            if (criticalControlId != Guid.Empty)
            {
                string ownerName = Services.CriticalControlV2Service.GetCriticalControlOwnerName(criticalControlId);
                IEnumerable<string> champions = Services.CriticalControlV2Service.GetCriticalControlChampions(criticalControlId);
                return Json(new { ownerName, champions });
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        #region Create Critical Control

        [HttpGet]
        public ActionResult CreateCriticalControl(Guid majorHazardId)
        {
            if (majorHazardId != Guid.Empty)
            {
                EditCriticalControlV2ViewModel viewModel = Services.CriticalControlV2Service
                                                                    .PopulateCriticalControlEditModel(majorHazardId);

                ViewBag.Title = "New";
                return PartialView("~/Views/Safety/v2/CriticalControl/_EditCriticalControlV2Form.cshtml", viewModel);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCriticalControl(EditCriticalControlV2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.CriticalControlV2Service.AddCriticalControl(model);
                return Content("ok");
            }

            ViewBag.Title = "New";
            Services.CriticalControlV2Service.PopulateCriticalControlEditModel(model);
            return PartialView("~/Views/Safety/v2/CriticalControl/_EditCriticalControlV2Form.cshtml", model);
        }

        #endregion

        #region Edit Critical Control

        [HttpGet]
        public ActionResult EditCriticalControl(Guid criticalControlId)
        {
            if (criticalControlId != Guid.Empty)
            {
                EditCriticalControlV2ViewModel viewModel = Services.CriticalControlV2Service.GetCriticalControlForEdit(criticalControlId);
                ViewBag.Title = "Edit";
                return PartialView("~/Views/Safety/v2/CriticalControl/_EditCriticalControlV2Form.cshtml", viewModel);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCriticalControl(EditCriticalControlV2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.CriticalControlV2Service.UpdateCriticalControl(model);
                return Content("ok");
            }

            ViewBag.Title = "Edit";
            Services.CriticalControlV2Service.PopulateCriticalControlEditModel(model);
            return PartialView("~/Views/Safety/v2/CriticalControl/_EditCriticalControlV2Form.cshtml", model);
        }

        #endregion


    }
}

Relay.Web/Controllers/Safety/v2/SafetyMajorHazardsV2Controller.cs
using System;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using MomentumPlus.Relay.Models;
using System.Collections.Generic;
using System.Net;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class SafetyMajorHazardsV2Controller : BaseController
    {
        public SafetyMajorHazardsV2Controller(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }


        public ActionResult Index()
        {
            IEnumerable<MajorHazardV2ViewModel> majorHazardsViewModel = Services.MajorHazardV2Service.GetAllMajorHazards();
            return View("~/Views/Safety/v2/MajorHazards/Index.cshtml", majorHazardsViewModel);
        }

        [HttpPost]
        public ActionResult GetMajorHazardInfo(Guid majorHazardId)
        {
            if (majorHazardId == Guid.Empty)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            MajorHazardV2ViewModel model = Services.MajorHazardV2Service.GetMajorHazard(majorHazardId);
            return Json(model);
        }

        [HttpGet]
        public ActionResult EditMajorHazardDialog(Guid majorHazardId)
        {
            if (majorHazardId == Guid.Empty)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            EditMajorHazardV2ViewModel model = Services.MajorHazardV2Service.GetMajorHazardForEdit(majorHazardId);
            return PartialView("~/Views/Safety/v2/MajorHazards/_EditMajorHazardV2Dialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditMajorHazardDialog(EditMajorHazardV2ViewModel model)
        {
            if(model.Id == Guid.Empty)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Services.MajorHazardV2Service.UpdateMajorHazard(model);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

    }
}

Relay.Web/Controllers/Safety/v2/SafetyMessageV2Controller.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class SafetyMessageV2Controller : BaseController
    {
        //IOC
        public SafetyMessageV2Controller(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }

        public ActionResult SafetyMessagePreviewDialog(Guid safetyMessageId)
        {
            SafetyMessageV2ViewModel safetyMessage = Services.SafetyMessageV2Service.GetSafetyMessage(safetyMessageId);

            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessagePreviewV2Dialog.cshtml", safetyMessage);
        }

        [HttpGet]
        public ActionResult GetSafetyMessagesForUser(DateTime? date)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            if (date.HasValue)
            {
                IEnumerable<SafetyMessageV2ViewModel> model = Services.SafetyMessageV2Service.GetSafetyMessagesForUser(date.Value, userId);

                return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageV2Dialog.cshtml", model);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult SetSafetyMessageShowForUser(Guid safetyMessageId)
        {
            if(safetyMessageId != Guid.Empty)
            {
                Guid userId = Guid.Parse(User.Identity.GetUserId());
                Services.SafetyMessageV2Service.SetSafetyMessageShowForUser(safetyMessageId, userId);

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
    }
}

Relay.Web/Controllers/Safety/v2/SafetyShedulerV2Controller.cs
using System;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using MomentumPlus.Relay.Models;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class SafetyShedulerV2Controller : BaseController
    {
        //IOC
        public SafetyShedulerV2Controller(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }

        public ActionResult Index()
        {
            return View("~/Views/Safety/v2/Sheduler/Index.cshtml");
        }

        [HttpGet]
        public ActionResult GetFullCalendar(DateTime? date)
        {
            DateTime calsendarDate = date.HasValue ? date.Value : DateTime.UtcNow;

            SafetyCalendarV2ViewModel model = Services.SafetyMessageV2Service.GetSafetyCalendar(calsendarDate);

            return PartialView("~/Views/Safety/v2/Sheduler/_CalendarFull.cshtml", model);
        }

        [HttpGet]
        public ActionResult GetMinCalendar(DateTime? date)
        {
            DateTime activeDay = DateTime.Today.AddDays(1);
            DateTime calendarDate = (date.HasValue && date.Value >= activeDay) ? date.Value : activeDay;

            SafetyCalendarV2ViewModel model = Services.SafetyMessageV2Service.GetSafetyCalendar(calendarDate);

            ModelState.Remove("Date");

            return PartialView("~/Views/Safety/v2/Sheduler/_CalendarMin.cshtml", model);
        }

        [HttpGet]
        public ActionResult SafetyMessagesForDateDialog(DateTime date)
        {
            var model = Services.SafetyMessageV2Service.GetSafetyMessagesForDate(date);

            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessagesForDateV2Dialog.cshtml", model);
        }

        #region Add Safety Message

        [HttpGet]
        public ActionResult AddSafetyMessageDialog(DateTime? date)
        {
            EditSafetyMessageV2ViewModel model = Services.SafetyMessageV2Service.PopulateEditSafetyMessageModel(date);

            ViewBag.Title = "Schedule Safety Message";
            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageV2FormDialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSafetyMessageDialog(EditSafetyMessageV2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.SafetyMessageV2Service.AddSafetyMessage(model);
                return Content("ok");
            }

            ViewBag.Title = "Schedule Safety Message";
            Services.SafetyMessageV2Service.PopulateEditSafetyMessageModel(model);
            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageV2FormDialog.cshtml", model);
        }

        #endregion

        #region Edit Safety Message

        [HttpGet]
        public ActionResult EditSafetyMessageDialog(Guid safetyMessageId)
        {
            EditSafetyMessageV2ViewModel model = Services.SafetyMessageV2Service.GetSafetyMessageForEdit(safetyMessageId);

            ViewBag.Title = "Edit Safety Message";
            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageV2FormDialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSafetyMessageDialog(EditSafetyMessageV2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.SafetyMessageV2Service.UpdateSafetyMessage(model);
                return Content("ok");
            }

            ViewBag.Title = "Edit Safety Message";
            Services.SafetyMessageV2Service.PopulateEditSafetyMessageModel(model);
            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageV2FormDialog.cshtml", model);
        }

        #endregion

        #region Reschedule Safety Message

        [HttpGet]
        public ActionResult RescheduleSafetyMessageDialog(Guid safetyMessageId)
        {
            SafetyMessageRescheduleV2ViewModel model = Services.SafetyMessageV2Service.GetSafetyMessageForRescheduling(safetyMessageId);

            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageRescheduleV2Dialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RescheduleSafetyMessageDialog(SafetyMessageRescheduleV2ViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.SafetyMessageV2Service.RescheduleSafetyMessage(model);
                return Content("ok");
            }

            return PartialView("~/Views/Safety/v2/Sheduler/_SafetyMessageRescheduleV2Dialog.cshtml", model);
        }

        #endregion
    }

}

Relay.Web/Views/Safety/v2/Sheduler/Index.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Main/Authorized_Layout.cshtml";
}

<div class="safety-scheduler-v2-page">
    <div class="page-content">
        <div class="scheduler-container">
            <div class="container-calendar-v2">
                <div class="row">
                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 calendar-container">
                        @Html.Action("GetFullCalendar", "SafetyShedulerV2")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Content/js/relay/url-hash.module.js"></script>
<script src="~/Content/js/relay/safety/v2/scheduler-v2.module.js"></script>

Relay.Web/Views/Safety/v2/Sheduler/_CalendarFull.cshtml
@model SafetyCalendarV2ViewModel

@Html.Hidden("CalendarDate", Model.Date.ToISOString())

<table class="table-condensed table-bordered">
    <thead>
        <tr>
            <td colspan="7" class="pagination-cell">
                <div class="pagination-pages">
                    <button class="prev-page"></button>
                    <div class="page">@Model.MonthYear</div>
                    <button class="next-page"></button>
                </div>
            </td>
        </tr>
        <tr>
            <th>Mon</th>
            <th>Tue</th>
            <th>Wed</th>
            <th>Thu</th>
            <th>Fri</th>
            <th>Sat</th>
            <th>Sun</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Dates.Length; i += 7)
        {
            <tr>
                @for (int j = 0; j < 7; ++j)
                {
                    bool notActive = Model.Dates[i + j].Date.Month != Model.Date.Month || Model.Dates[i + j].Date <= Model.CurrentDate;

                    string viewClass = (Model.Dates[i + j].Date.Month != Model.Date.Month) ? "view" : "";

                    <td date="@Model.Dates[i+j].Date.ToISOString()">
                        <p class="@viewClass">@Model.Dates[i + j].Date.Day</p>

                        @if (@Model.Dates[i + j].MessagesNumber == 0)
                        {
                            if (!notActive)
                            {
                                <div class="plus"></div>
                            }
                        }
                        else
                        {
                            if (@Model.Dates[i + j].MessagesNumber == 1)
                            {
                                <img src="@Model.Dates[i + j].IconUrl" class="@viewClass">
                            }
                            else
                            {
                                <div class="many-messages @viewClass">@Model.Dates[i + j].MessagesNumber</div>
                            }

                            if (!notActive)
                            {
                                <div class="plus-down"></div>
                            }
                        }
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Relay.Web/Views/Safety/v2/Sheduler/_CalendarMin.cshtml
@model SafetyCalendarV2ViewModel

@Html.Hidden("Date", Model.Date.ToISOString())
<div class="safety-schedule-message-mini-calendar">
    <table cellspacing="0">
        <thead>
            <tr>
                <td colspan="7" class="pagination-cell">
                    <div class="calendar-controls">
                        @{
                            DateTime firstActiveDate = Model.CurrentDate.AddDays(1);
                            bool isFirstMonth = Model.Date.Year == firstActiveDate.Year && Model.Date.Month == firstActiveDate.Month;
                        }
                        <button type="button" class="@(isFirstMonth ? "inactive" : "") calendar-previous"></button>
                        <div class="month-name">@Model.MonthYear</div>
                        <button type="button" class="calendar-next"></button>
                    </div>
                </td>
            </tr>
            <tr>
                <th>Mon</th>
                <th>Tue</th>
                <th>Wed</th>
                <th>Thu</th>
                <th>Fri</th>
                <th>Sat</th>
                <th>Sun</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Dates.Length; i += 7)
            {
                <tr>
                    @for (int j = 0; j < 7; ++j)
                    {
                        string cellClass = string.Empty;

                        if(Model.Date == Model.Dates[i + j].Date)
                        {
                            cellClass += "blue";
                        }
                        else
                        {
                            if (Model.Dates[i + j].MessagesNumber > 0)
                            {
                                cellClass += "orange";
                            }
                            if(Model.Dates[i + j].Date.Month != Model.Date.Month || Model.Dates[i + j].Date <= Model.CurrentDate)
                            {
                                cellClass += " gray";
                            }
                        }

                        <td date="@Model.Dates[i+j].Date.ToISOString()" class="@cellClass">
                            @Model.Dates[i + j].Date.Day
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

Relay.Web/Views/Safety/v2/Sheduler/_SafetyMessagePreviewV2Dialog.cshtml
@model SafetyMessageV2ViewModel

<div Id="safetyMessagePreviewV2Dialog" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true" class="modal fade safety-message-v2-dialog">
    <div class="page-content">
        <div class="modal-dialog modal-sm">
            <div class="theme">
                <div class="modal-content no-padding">
                    <div class="modal-header">
                        <div class="row no-margin">
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 no-padding left-block">
                                @*<button type="button" data-dismiss="modal" class="arrow-forward-btn next-safety"></button>*@
                            </div>
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 no-padding">
                                <div class="row no-margin">
                                    <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 no-padding">
                                        <div class="padding-left-20 margin-top-20 bold">Critical Control</div>
                                    </div>
                                    <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6  no-padding text-right">
                                        <button type="button" data-dismiss="modal" aria-hidden="true" class="btn margin-right-20 btn-close" style="margin-top: 23px;"></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-body">
                        <div class="row no-margin">
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 no-padding left-block yellow-block">
                                <img src="@Model.IconUrl" class="message-icon">
                                <div class="title">Major Hazard</div>
                                <div class="title">@Model.MajorHazardName</div>
                            </div>
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 right-block">
                                <div class="title">@Model.CriticalControlName</div>
                                <div class="message">@Model.Message</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Relay.Web/Views/Safety/v2/Sheduler/_SafetyMessageRescheduleV2Dialog.cshtml
@model SafetyMessageRescheduleV2ViewModel

<div Id="rescheduleSafetyMessageV2Dialog" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static" class="modal fade safety-reschedule-message-v2-dialog">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="modal-dialog ">
            <div class="theme">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row vertical-center">
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                <div class="modal-title">Reschedule Safety Message</div>
                            </div>
                            <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
                                <button type="submit" class="btn btn-save">Save</button>
                                <button type="button" data-dismiss="modal" aria-hidden="true" class="btn btn-close"></button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                                <div class="row">
                                    <div class="col col-lg-7 col-md-7 col-sm-7 col-xs-7">
                                        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 major-hazard no-padding">
                                            <div class="field-container">
                                                @Html.HiddenFor(m => m.MajorHazardId)
                                                @Html.LabelFor(m => m.MajorHazardId, new { @class = "title-select" })
                                                @Html.TextBoxFor(m => m.MajorHazardName, new { @class = "simple-input", @readonly = "" })
                                            </div>
                                        </div>
                                        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding critical-control">
                                            <div class="field-container">
                                                @Html.HiddenFor(m => m.CriticalControlId)
                                                @Html.LabelFor(m => m.CriticalControlId, new { @class = "title-select" })
                                                @Html.TextBoxFor(m => m.CriticalControlName, new { @class = "simple-input", @readonly = "" })
                                            </div>
                                        </div>
                                        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding critical-control-owner">
                                            @Html.LabelFor(m => m.CriticalControlOwnerName, new { @class = "title-select" })
                                            @if (!string.IsNullOrEmpty(Model.CriticalControlOwnerName))
                                            {
                                                <div class="critical-control-owner-name">@Model.CriticalControlOwnerName</div>
                                            }
                                            else
                                            {
                                                <div class="empty-critical-control-owner-name">Critical Control Owner</div>
                                            }
                                        </div>
                                        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding critical-control-champion-list">
                                            @Html.LabelFor(m => m.CriticalControlChampions, new { @class = "title-select" })
                                            @if (Model.CriticalControlChampions.Any())
                                            {
                                                foreach (string championName in Model.CriticalControlChampions)
                                                {
                                                    <div class="critical-control-champion">@championName</div>
                                                }
                                            }
                                            else
                                            {
                                                <div class="empty-critical-control-champions">Critical Control Champion(s)</div>
                                            }
                                        </div>
                                    </div>
                                    <div class="col col-lg-5 col-md-5 col-sm-5 col-xs-5 mini-calendar">
                                        @Html.Action("GetMinCalendar", new { date = Model.Date })
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 sefety-message-text">
                                        <div class="field-container">
                                            @Html.LabelFor(m => m.Message, new { @class = "title-select" })
                                            @Html.TextAreaFor(m => m.Message, new { @class = "textarea simple-textarea", @rows = "3", @maxlength = "250", @placeholder = "Enter Message (250 characters)" })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <script src="~/Content/js/relay/safety/v2/dialogs/calendar-mini-v2.module.js"></script>
    <script>
        (function () {
            //------------------------------------------
            setTimeout(initChampionsList, 200);
            //------------------------------------------
            function initChampionsList() {

                var removedElements = 0;
                var elementsHeight = 0;

                $("#rescheduleSafetyMessageV2Dialog .critical-control-champion").each(function (index, element) {
                    var elementHeight = $(element).width() + 10;

                    if (elementsHeight + elementHeight < 260) {
                        elementsHeight += elementHeight;
                    }
                    else {
                        $(element).remove();
                        removedElements++;
                    }
                });

                if (removedElements) {
                    var numberDiv = document.createElement("div");
                    numberDiv.className = "critical-control-champion";
                    numberDiv.textContent = '+' + removedElements.toString();

                    $("#rescheduleSafetyMessageV2Dialog .critical-control-champion-list")[0].appendChild(numberDiv);
                }
            }
            //------------------------------------------
        })();
    </script>
</div>