Relay.Web/Controllers/MediaController.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MomentumPlus.Core.Models;
using System.Web.UI;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class MediaController : BaseController
    {
        //IOC
        public MediaController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        public ActionResult GetFile(Guid Id)
        {
            if (Id == Guid.Empty)
                return HttpNotFound();

            FileViewModel file = Services.MediaService.GetFile(Id);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }

        [HttpGet]
        public ActionResult GetAttachment(Guid Id)
        {
            if (Id == Guid.Empty)
                return HttpNotFound();

            FileViewModel file = Services.AttachmentService.GetAttachment(Id);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType, file.FileName);
        }



        [AllowAnonymous]
        public ActionResult GetImage(Guid imageId, int? width = null, int? height = null)
        {
            if (imageId == Guid.Empty)
                return HttpNotFound();

            FileViewModel img = Services.MediaService.GetImage(imageId, width, height);

            if (img == null)
                return HttpNotFound();

            return File(img.BinaryData, img.ContentType);
        }

        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client, VaryByParam = "employeeId")]
        public ActionResult GetAvatarForEmployee(Guid employeeId, int? width, int? height)
        {
            if (employeeId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(employeeId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult GetMyAvatar(int? width, int? height)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());

            FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(userId, width, height);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }

        public ActionResult GetProjectAvatar(Guid projectId, int? width, int? height)
        {
            if (projectId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetProjectAvatarImage(projectId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

        public ActionResult ShowNumberOfRemainingTrialDaysForUser()
        {
            var employeeId = Guid.Parse(User.Identity.GetUserId());

            if (employeeId != Guid.Empty)
            {
                string result = string.Empty;

                if (Services.AuthService.IsTrialSubscription(employeeId))
                {
                    var remainingTrialDays = Services.AuthService.NumberOfRemainingTrialDays(employeeId);
                    result = remainingTrialDays + " Days Remaining on Trial";
                }

                return PartialView("~/Views/Rotation/Shared/ShowNumberOfRemainingTrialDaysForUser.cshtml", result);
            }

            return HttpNotFound();
        }

    }
}

Relay.Web/Controllers/Rotation/ShiftReportBuilder/ShiftTaskBoardTasksSectionController.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class ShiftTaskBoardTasksSectionController : BaseController
    {
        // IOC
        public ShiftTaskBoardTasksSectionController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        [HttpGet]
        public ActionResult Draft(Guid shiftId, HandoverReportFilterType filter = HandoverReportFilterType.All)
        {
            IEnumerable<TaskBoardTaskForHandover> model = Services.TaskBoardTaskService
                                                                .GetTaskBoardTasksForShift(shiftId, ModuleSourceType.Draft)
                                                                .OrderBy(t => t.Name);

            return PartialView("~/Views/Rotation/ShiftReportBuilder/TaskBoardTasks/_TaskBoardTasksDraftSection.cshtml", model);
        }

        [HttpGet]
        public ActionResult Received(Guid shiftId, Guid? receivedShiftId)
        {
            IEnumerable<TaskBoardTaskForHandover> model = Services.TaskBoardTaskService
                                                                .GetTaskBoardTasksForShift(shiftId, ModuleSourceType.Received, receivedShiftId)
                                                                .OrderBy(t => t.Name);


            return PartialView("~/Views/Rotation/ShiftReportBuilder/TaskBoardTasks/_TaskBoardTasksReceivedSection.cshtml", model);
        }


        [HttpPost]
        public ActionResult ReloadTask(Guid topicId)
        {
            if (topicId != Guid.Empty)
            {
                TaskBoardTaskForHandover model = Services.TaskBoardTaskService.GetTask(topicId);
                if (model != null)
                {
                    return Json(model);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult UpdateTask(TaskBoardTaskForHandover model)
        {

            return Json(model);
        }


    }
}

Relay.Web/Controllers/Rotation/TopicController.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Web.Mvc;
using System.Net;
using Microsoft.AspNet.Identity;
using MomentumPlus.Relay.Roles;
using System.Collections.Generic;
using System.Web.UI;
using System.Text.RegularExpressions;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class TopicController : BaseController
    {
        // IOC
        public TopicController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        public ActionResult EditTopicDialog(Guid topicid)
        {
            ModuleType section = Services.RotationTopicService.GetTopicModuleType(topicid);

            switch (section)
            {
                case ModuleType.HSE:
                    return RedirectToAction("EditTopicDialog", "HSESection", new { topic = topicid });
                case ModuleType.Core:
                    return RedirectToAction("EditTopicDialog", "CoreSection", new { topic = topicid });
                case ModuleType.Project:
                    return RedirectToAction("EditTopicDialog", "ProjectsSection", new { topic = topicid });
                case ModuleType.Team:
                    return RedirectToAction("EditTopicDialog", "TeamSection", new { topic = topicid });

                case ModuleType.DailyNote:
                default:
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        [HttpGet]
        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client)]
        public ActionResult ManagerCommentButton(ManagerCommentButtonViewModel model)
        {
            if (model.ItemId.HasValue)
            {
                Guid userId = Guid.Parse(User.Identity.GetUserId());

                var isMyTopic = Services.RotationTopicService.IsMyTopic(userId, model.ItemId.Value);

                if (User.IsInRole(iHandoverRoles.Relay.iHandoverAdmin) && !isMyTopic ||
                    User.IsInRole(iHandoverRoles.Relay.ExecutiveUser) && !isMyTopic ||
                    User.IsInRole(iHandoverRoles.Relay.Administrator) && !isMyTopic ||
                    User.IsInRole(iHandoverRoles.Relay.HeadLineManager) && !isMyTopic ||
                    User.IsInRole(iHandoverRoles.Relay.LineManager) && !isMyTopic)
                {
                    model.IsActive = true;
                }
            }

            return PartialView("~/Views/Rotation/Shared/ManagerComments/_ManagerCommentButton.cshtml", model);
        }

        [HttpGet]
        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client)]
        public ActionResult TopicDetailsDialog(Guid topicid)
        {
            var model = Services.RotationTopicService.GetModelForTopicDetailsModal(topicid);
            return PartialView("~/Views/Rotation/Topic/_ViewTopicDetailsDialog.cshtml", model);
        }

        [HttpGet]
        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client)]
        public ActionResult ManagerCommentsDialog(Guid Id)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            var isEditable = Services.RotationTopicService.IsMyTopic(userId, Id)
                                 || Services.RotationTopicService.IsCanChangeTopic(userId, Id)
                                 || Services.RotationTopicService.IsContributersTopicUser(userId, Id)
                                 || (User.IsInRole(iHandoverRoles.Relay.iHandoverAdmin)
                                 || User.IsInRole(iHandoverRoles.Relay.Administrator)
                                 || User.IsInRole(iHandoverRoles.Relay.HeadLineManager)
                                 || User.IsInRole(iHandoverRoles.Relay.LineManager)
                                 || User.IsInRole(iHandoverRoles.Relay.ExecutiveUser));

            IEnumerable<ManagerCommentsViewModel> model = Services.RotationTopicService.PopulateManagerCommentsViewModel(Id, SwingOwnerId);

            if (isEditable)
            {
                return PartialView("~/Views/Rotation/Shared/ManagerComments/_NewManagerCommentsFormDialog.cshtml", model);
            }

            return PartialView("~/Views/Rotation/Shared/ManagerComments/_NewManagerCommentsDetailsDialog.cshtml", model);
        }


        [HttpGet]
        public ActionResult TopicComments(Guid Id)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            var isEditable = Services.RotationTopicService.IsMyTopic(userId, Id)
                                 || Services.RotationTopicService.IsCanChangeTopic(userId, Id)
                                 || Services.RotationTopicService.IsContributersTopicUser(userId, Id)
                                 || (User.IsInRole(iHandoverRoles.Relay.iHandoverAdmin)
                                 || User.IsInRole(iHandoverRoles.Relay.Administrator)
                                 || User.IsInRole(iHandoverRoles.Relay.HeadLineManager)
                                 || User.IsInRole(iHandoverRoles.Relay.LineManager)
                                 || User.IsInRole(iHandoverRoles.Relay.ExecutiveUser));

            IEnumerable<ManagerCommentsViewModel> model = Services.RotationTopicService.PopulateManagerCommentsViewModel(Id, SwingOwnerId);

            return PartialView("~/Views/Rotation/Topic/_TopicComments.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ManagerCommentsDialog(ManagerCommentsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.RotationTopicService.UpdateTopicManagerComment(model, SwingOwnerId);
                return Content("ok");
            }

            return PartialView("~/Views/Rotation/Shared/ManagerComments/_NewManagerCommentsFormDialog.cshtml", model);
        }

        [HttpGet]
        public ActionResult AddManagerCommentsForTopic(Guid Id)
        {
            if (Id != Guid.Empty)
            {
                ManagerCommentsViewModel managerComments = new ManagerCommentsViewModel {  Id = Id };
                return PartialView("~/Views/Rotation/Shared/ManagerComments/_AddManagerCommentsFormDialog.cshtml", managerComments);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddManagerCommentsForTopic(ManagerCommentsViewModel model)
        {
            if (model.Id != null)
            {
                if (ModelState.IsValid)
                {
                    Services.RotationTopicService.UpdateTopicManagerComment(model, SwingOwnerId);
                    return Content("ok");
                }
                else
                {
                    return PartialView("~/Views/Rotation/Shared/ManagerComments/_AddManagerCommentsFormDialog.cshtml", model);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult RemoveManagerCommentsDialog(Guid? id, Guid? managerCommentId)
        {
            if (id != null && managerCommentId != null)
            {
                Services.RotationTopicService.RemoveTopicManagerComment(id.Value, managerCommentId.Value);
                return Content("ok");
            }

            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult EditManagerCommentsForTopic(Guid topicId, Guid managerCommentId)
        {
            if (topicId != Guid.Empty)
            {
                ManagerCommentsViewModel managerComments = Services.RotationTopicService.GetManagerCommentsViewModel(topicId, managerCommentId);

                return PartialView("~/Views/Rotation/Shared/ManagerComments/_EditManagerComments.cshtml", managerComments);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditManagerCommentsForTopic(ManagerCommentsViewModel model)
        {
            if (model.Id != null)
            {
                if (ModelState.IsValid)
                {
                    Services.RotationTopicService.UpdateTopicManagerComment(model, SwingOwnerId);
                    return Content("ok");
                }
                else
                {
                    return PartialView("~/Views/Rotation/Shared/ManagerComments/_EditManagerCommentsFormDialog.cshtml", model);
                }
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult CarryforwardTopic(Guid topicId)
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());
            Services.RestrictionService.TopicsCarryForwardsLimitExceeded(topicId);
            Services.RotationTopicService.CarryforwardTopic(topicId);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult RemoveTopic(Guid topicId)
        {
            if (topicId != Guid.Empty && Services.RotationTopicService.RemoveTopic(topicId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        #region Location

        [HttpGet]
        public ActionResult DetailsLocationFormDialog(Guid topicId)
        {
            LocationViewModel model = Services.LocationService.GetLocationForTopic(topicId);
            if (model != null)
            {
                return PartialView("~/Views/Rotation/Topic/_LocationDetailsFormDialog.cshtml", model);
            }

            return HttpNotFound();
        }

        [HttpGet]
        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client)]
        public ActionResult CreateLocationFormDialog(Guid topicId)
        {
            if (topicId != Guid.Empty)
            {
                TempData["CreateLocation_TopicId"] = topicId;

Relay.Web/Views/Rotation/ShiftReportBuilder/ProjectsSection/_ProjectAddInlineTopic.cshtml
@model ShiftProjectAddInlineTopicViewModel

<tr class="new-line">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ShiftId)
    @Html.HiddenFor(m => m.CreatorId)

    <td class="actions-body">
        <div class="btn remove-btn btn-circle tooltipster" @Html.TooltipAttritutes("Remove")><span class="glyphicon span"></span></div>

        @*<div class="btn hand-back-inactive-btn btn-circle tooltipster" @Html.TooltipAttritutes("Hand-back")><span class="glyphicon span"></span></div>*@

        <div class="btn pin-grey-btn btn-circle tooltipster" @Html.TooltipAttritutes("Pin")><span class="glyphicon span"></span></div>
    </td>
    <td class="type-body" style="padding-bottom: 38px;">
        <div class="select-parameter">
            @Html.DropDownListFor(m => m.Project, Model.Projects, null, new { @title = "Select", @class = "select-type" })
        </div>
    </td>
    <td class="reference-body">
        @Html.TextBoxFor(model => model.Reference, new { @class = "input-field text-blue add-reference", @placeholder = "Add Reference" })
    </td>
    <td class="notes-body">
        @Html.TextAreaFor(model => model.Notes, new { @class = "new-note text-blue add-note", @placeholder = "Add Notes", @maxlength = "1000" })
        <div class="accept-btn accept-btn-grey"></div>
    </td>
    <td class="tags-body" style="width:200px;"></td>
    <td class="intel-body">
        <button type="button" class="inline-add-btn tooltipster" @Html.TooltipAttritutes("Add topic")>
            Add
        </button>
        <div class="other-actions">
            <button class="action-btn hand-back-inactive-btn tooltipster" @Html.TooltipAttritutes("Hand-back")></button>
        </div>
    </td>
</tr>

<script>
    var trElement = $(".new-line");

    $('.select-type', trElement).change(function () {
        $('.add-reference', trElement).focus();
    });
</script>

Relay.Web/Views/Rotation/ShiftReportBuilder/ProjectsSection/_ProjectsReceivedSection.cshtml
@model IEnumerable<ProjectsTopicViewModel>

<div Id="projectsSection">
    <div class="panel-body grey-panel">
        <div class="navbar navbar-blue"><span class="label">@Html.EnumDescription(ModuleType.Project)</span></div>
    </div>
    <div class="table-block">
        @if (Model != null && Model.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th class="actions-title">Actions</th>
                        <th class="type-title">Topic</th>
                        <th class="reference-title">Reference</th>
                        <th class="notes-title">Notes</th>
                        <th class="intel-title"></th>
                        <th class="intel-title" style="width:120px !important;">Intel</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var topic in Model)
                    {
                    <tr>
                        @Html.Hidden("Id", topic.Id)
                        @Html.Hidden("CreatorId", topic.CreatorId)

                        <td class="actions-body">
                            @if (topic.IsNullReport)
                            {
                                <div class="btn btn-circle nr-active-btn tooltipster" @Html.TooltipAttritutes("Checked")>
                                    <span class="glyphicon span"></span>
                                </div>
                            }
                            else
                            {
                                <div class="btn btn-circle none-btn">
                                    <span class="glyphicon span"></span>
                                </div>
                            }

                            @if (topic.IsSharingTopic)
                            {
                                <div class="is-shared">S</div>
                            }
                            else
                            {
                                <div class="btn none-btn btn-circle">
                                    <span class="glyphicon span"></span>
                                </div>
                            }
                        </td>

                        @if (topic.IsFirstTopicByTopicGroupName.HasValue && topic.IsFirstTopicByTopicGroupName.Value)
                        {
                            <td class="type-body">
                                @topic.Project
                            </td>
                        }
                        else
                        {
                            <td class="type-body"></td>
                        }

                        <td class="reference-body">
                            @topic.Reference
                        </td>

                        <td class="notes-body">

                            @if (topic.PlannedActualHas.HasValue && topic.PlannedActualHas.Value || topic.PlannedActualField.IsExpandPlannedActualField.HasValue && topic.PlannedActualField.IsExpandPlannedActualField.Value)
                            {
                                <div class="plannedActual" topic-id="@topic.Id">
                                    @Html.Partial("~/Views/Rotation/Shared/ReceivedHistoryPvA.cshtml", topic.PlannedActualField)
                                </div>
                            }
                            else
                            {
                                <div class="plannedActual" style="display:none;" topic-id="@topic.Id">
                                    @Html.Partial("~/Views/Rotation/Shared/ReceivedHistoryPvA.cshtml", topic.PlannedActualField)
                                </div>
                            }

                            <span class="icon-text"></span>
                            <div class="plannedActualNoEdit" topic-id="@topic.Id">
                                @Html.Partial("~/Views/Rotation/Shared/NotEditPvA.cshtml", topic.PlannedActualField)
                            </div>
                          
                            <p class="note-short"> @(topic.Notes)</p>

                            <div class="field-of-edit">
                                <textarea class="change-note" maxlength="1000"></textarea>
                                <div topic-val="@topic.IsFinalized.ToString().ToLower()" class="accept-btn finalise-btn tooltipster" @Html.TooltipAttritutes("Finalise")></div>
                            </div>

                            @if (topic.TagsTopicField.HasTags.Value)
                            {
                                <div class="tags-recieved" topic-id="@topic.Id">
                                    @Html.Partial("~/Views/Rotation/Shared/RecievedTagsTopic.cshtml", Tuple.Create<string, Guid>(topic.TagsString, topic.Id.Value))
                                </div>
                            }
                            else
                            {
                                <div class="tags-recieved" style=" display:none;" topic-id="@topic.Id" topic-val="@topic.FirstTagTopic" topic-MoreTags="@topic.MoreTags">
                                    @Html.Partial("~/Views/Rotation/Shared/RecievedTagsTopic.cshtml", Tuple.Create<string, Guid>(topic.TagsString, topic.Id.Value))
                                </div>
                            }

                            <div class="contributes-users">
                                @Html.Partial("~/Views/Rotation/Shared/ShowIconContributorUsers.cshtml", topic.EditorUsers)
                            </div>

                        </td>

                        <td class="tags-body">
                            @Html.Partial("~/Views/Rotation/Shared/ShowTagsTopic.cshtml", topic.TagsTopicField)
                        </td>
                        <td class="intel-body">

                            @Html.Action("ManagerCommentButton", "Topic", new ManagerCommentButtonViewModel { ItemId = topic.Id.Value, HasComments = topic.HasComments })

                            <div class="btn btn-circle user-photo-btn team-btn tooltipster" topic-val="@topic.FromTeammateId.ToString()" @Html.TooltipAttritutes(topic.FromTeammateFullName)>
                                <img src="@Url.Action("GetAvatarForEmployee", "Media", new {area = "", employeeId = @topic.FromTeammateId, width = 100, height = 100})"
                                     class="user-photo-img" />
                            </div>

                            <div class="btn btn-circle more-btn tooltipster" @Html.TooltipAttritutes("Extras")>
                                <span class="glyphicon span"></span>
                            </div>
                            <div class="other-actions">
                                @*<button topic-val="@topic.HasTasks.ToString().ToLower()" class="action-btn tasks-btn tooltipster" @Html.TooltipAttritutes("Tasks")></button>*@
                                <button topic-val="@topic.IsFeedbackRequired.ToString().ToLower()" class="action-btn arrows-btn tooltipster" @Html.TooltipAttritutes("Hand-back")></button>
                                <button topic-val="@topic.HasLocation.ToString().ToLower()" class="action-btn location-btn tooltipster" @Html.TooltipAttritutes("Locations")></button>
                                <button topic-val="@topic.HasAttachments.ToString().ToLower()" class="action-btn attachments-btn tooltipster" @Html.TooltipAttritutes("Attachments")></button>
                                <button topic-val="@topic.HasTags.ToString().ToLower()" class="action-btn tags-btn tooltipster" @Html.TooltipAttritutes("Tags")></button>
                                @*<button topic-val="@topic.HasVoiceMessages.ToString().ToLower()" class="action-btn voice-msg-btn tooltipster" @Html.TooltipAttritutes("Voice Messages") disabled style="cursor: not-allowed !important"></button>*@
                                <button topic-val="@topic.PlannedActualHas.ToString().ToLower()" class="action-btn planned-actual-btn tooltipster" @Html.TooltipAttritutes("Planned & Actual")></button>
                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <div class="text-center" style="margin: 10px">@Html.EnumDescription(ModuleType.Project, "No {0} Items")</div>
        }
    </div>
</div>