Relay.Web/Controllers/MediaController.cs
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MomentumPlus.Core.Models;
using System.Web.UI;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class MediaController : BaseController
    {
        //IOC
        public MediaController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }

        public ActionResult GetFile(Guid Id)
        {
            if (Id == Guid.Empty)
                return HttpNotFound();

            FileViewModel file = Services.MediaService.GetFile(Id);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }

        [HttpGet]
        public ActionResult GetAttachment(Guid Id)
        {
            if (Id == Guid.Empty)
                return HttpNotFound();

            FileViewModel file = Services.AttachmentService.GetAttachment(Id);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType, file.FileName);
        }



        [AllowAnonymous]
        public ActionResult GetImage(Guid imageId, int? width = null, int? height = null)
        {
            if (imageId == Guid.Empty)
                return HttpNotFound();

            FileViewModel img = Services.MediaService.GetImage(imageId, width, height);

            if (img == null)
                return HttpNotFound();

            return File(img.BinaryData, img.ContentType);
        }

        [OutputCache(Duration = 200, Location = OutputCacheLocation.Client, VaryByParam = "employeeId")]
        public ActionResult GetAvatarForEmployee(Guid employeeId, int? width, int? height)
        {
            if (employeeId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(employeeId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
        public ActionResult GetMyAvatar(int? width, int? height)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());

            FileViewModel file = Services.MediaService.GetEmployeeAvatarImage(userId, width, height);

            if (file == null)
                return HttpNotFound();

            return File(file.BinaryData, file.ContentType);
        }

        public ActionResult GetProjectAvatar(Guid projectId, int? width, int? height)
        {
            if (projectId != Guid.Empty)
            {
                FileViewModel file = Services.MediaService.GetProjectAvatarImage(projectId, width, height);

                if (file == null)
                    return HttpNotFound();

                return File(file.BinaryData, file.ContentType);
            }

            return HttpNotFound();
        }

        public ActionResult ShowNumberOfRemainingTrialDaysForUser()
        {
            var employeeId = Guid.Parse(User.Identity.GetUserId());

            if (employeeId != Guid.Empty)
            {
                string result = string.Empty;

                if (Services.AuthService.IsTrialSubscription(employeeId))
                {
                    var remainingTrialDays = Services.AuthService.NumberOfRemainingTrialDays(employeeId);
                    result = remainingTrialDays + " Days Remaining on Trial";
                }

                return PartialView("~/Views/Rotation/Shared/ShowNumberOfRemainingTrialDaysForUser.cshtml", result);
            }

            return HttpNotFound();
        }

    }
}

Relay.Web/Controllers/Safety/v1/CriticalControlController.cs
using System;
using MomentumPlus.Relay.Models;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;

namespace MomentumPlus.Relay.Web.Controllers.Safety
{
    public class CriticalControlController : BaseController
    {
        //IOC
        public CriticalControlController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork){}

        #region Create Critical Control

        [HttpGet]
        public ActionResult CreateCriticalControl(Guid majorHazardId)
        {
            if (majorHazardId != Guid.Empty)
            {
                EditCriticalControlViewModel viewModel = Services.CriticalControlService.PopulateCriticalControlModel();
                viewModel.MajorHazardId = majorHazardId;

                ViewBag.Title = "New";
                return PartialView("~/Views/Safety/v1/CriticalControl/_EditCriticalControlForm.cshtml", viewModel);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCriticalControl(EditCriticalControlViewModel model)
        {
            if(ModelState.IsValid)
            {
                Services.CriticalControlService.AddCriticalControl(model);
                return Content("ok");
            }

            ViewBag.Title = "New";
            Services.CriticalControlService.PopulateCriticalControlModel(model);
            return PartialView("~/Views/Safety/v1/CriticalControl/_EditCriticalControlForm.cshtml", model);
        }

        #endregion

        #region Edit Critical Control

        [HttpGet]
        public ActionResult EditCriticalControl(Guid criticalControlId)
        {
            if (criticalControlId != Guid.Empty)
            {
                EditCriticalControlViewModel viewModel = Services.CriticalControlService.GetCriticalControl(criticalControlId);
                ViewBag.Title = "Edit";
                return PartialView("~/Views/Safety/v1/CriticalControl/_EditCriticalControlForm.cshtml", viewModel);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCriticalControl(EditCriticalControlViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.CriticalControlService.UpdateCriticalControl(model);
                return Content("ok");
            }

            ViewBag.Title = "Edit";
            Services.CriticalControlService.PopulateCriticalControlModel(model);
            return PartialView("~/Views/Safety/v1/CriticalControl/_EditCriticalControlForm.cshtml", model);
        }

        #endregion
    }
}

Relay.Web/Controllers/Safety/v1/MajorHazardController.cs
using System;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using MvcPaging;
using MomentumPlus.Relay.Models;
using System.Collections.Generic;

namespace MomentumPlus.Relay.Web.Controllers
{
    public class MajorHazardController : BaseController
    {
        public MajorHazardController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }

        public ActionResult Index(int? page)
        {
            var majorHazardsViewModel = Services.MajorHazardService.GetAll().ToPagedList(page - 1 ?? 0, 16);
            return View("~/Views/Safety/v1/MajorHazard/MajorHazardList.cshtml", majorHazardsViewModel);
        }

        public ActionResult NewMajorHazard()
        {
            return PartialView("~/Views/Safety/v1/MajorHazard/CreateMajorHazard.cshtml", new EditMajorHazardViewModel());
        }


        [HttpGet]
        public ActionResult EditMajorHazardDialog(Guid majorHazardId)
        {
            if (majorHazardId != Guid.Empty)
            {
                IEnumerable<CriticalControlViewModel> model = Services.CriticalControlService.GetCriticalControlsByMajorHazard(majorHazardId);
                return PartialView("~/Views/Safety/v1/MajorHazard/_EditMajorHazardDialog.cshtml", model);
            }
            
            return HttpNotFound();
        }

        [HttpGet]
        public ActionResult AddMajorHazard()
        {
            return PartialView("~/Views/Safety/v1/MajorHazard/CreateMajorHazard.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMajorHazard(EditMajorHazardViewModel model)
        {
            if(ModelState.IsValid)
            {
                Services.MajorHazardService.AddMajorHazard(model);
                return Content("ok");
            }
            
            return PartialView("~/Views/Safety/v1/MajorHazard/CreateMajorHazard.cshtml", model);
        }

    }
}

Relay.Web/Controllers/Safety/v1/ScheduleMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MomentumPlus.Relay.Interfaces;
using System.Web.Mvc;
using MomentumPlus.Relay.Models;
using System.Net;
using System.Web.Security;
using MomentumPlus.Relay.Roles;
namespace MomentumPlus.Relay.Web.Controllers
{
    public class ScheduleMessageController : BaseController
    {
        //IOC
        public ScheduleMessageController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork) { }

        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult Index()
        {
            SchedulerViewModel model = new SchedulerViewModel
            {
                Teams = Services.TeamService.GetTeamList()
            };

            return View("~/Views/Safety/v1/ScheduleMessage/_Scheduler.cshtml", model);
        }

        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult GetFullCalendar(DateTime? date, Guid? teamId)
        {
            DateTime calsendarDate = date.HasValue ? date.Value : DateTime.UtcNow;

            SafetyCalendarViewModel model = Services.SafetyMessageService.GetSafetyCalendar(calsendarDate, teamId);

            return PartialView("~/Views/Safety/v1/ScheduleMessage/_CalendarFull.cshtml", model);
        }

        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult GetMinCalendar(DateTime? date)
        {
            DateTime calsendarDate = date.HasValue ? date.Value : DateTime.UtcNow;

            SafetyCalendarViewModel model = Services.SafetyMessageService.GetSafetyCalendar(calsendarDate);

            ModelState.Remove("Date");

            return PartialView("~/Views/Safety/v1/ScheduleMessage/_CalendarMin.cshtml", model);
        }

        [HttpPost]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult GetCriticalControlsForMajorHazard(Guid majorHazardId)
        {
            if (majorHazardId != Guid.Empty)
            {
                IEnumerable<SelectListItem> criticalContrils = Services.CriticalControlService.GetCriticalControlsListByMajorHazard(majorHazardId);
                return Json(criticalContrils.Select(cc => new { Id = cc.Value, Name = cc.Text }));
            }

            return HttpNotFound();
        }

        [HttpPost]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult GetTeamsForCriticalControl(Guid criticalControlId)
        {
            if (criticalControlId != Guid.Empty)
            {
                IEnumerable<SelectListItem> teams = Services.TeamService.GetTeamListByCriticalControl(criticalControlId);
                return Json(teams.Select(cc => new { Id = cc.Value, Name = cc.Text }));
            }

            return HttpNotFound();
        }

        #region Add Safety Message

        [HttpGet]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult AddSafetyMessageDialog(DateTime? date)
        {
            EditSafetyMessageViewModel model = Services.SafetyMessageService.PopulateSafetyMessageModel();

            model.Date = date.HasValue ? date.Value : DateTime.Now;

            return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessageFormDialog.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult AddSafetyMessageDialog(EditSafetyMessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.SafetyMessageService.AddSafetyMessage(model);
                return Content("ok");
            }

            Services.SafetyMessageService.PopulateSafetyMessageModel(model);
            return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessageFormDialog.cshtml", model);
        }

        #endregion

        #region Edit Safety Message

        [HttpGet]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult EditSafetyMessageDialog(Guid safetyMessageId)
        {
            EditSafetyMessageViewModel model = Services.SafetyMessageService.GetSafetyMessage(safetyMessageId);
            if (model != null)
            {
                return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessageFormDialog.cshtml", model);
            }

            return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult EditSafetyMessageDialog(EditSafetyMessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.SafetyMessageService.UpdateSafetyMessage(model);
                return Content("ok");
            }

            Services.SafetyMessageService.PopulateSafetyMessageModel(model);
            return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessageFormDialog.cshtml", model);
        }

        #endregion

        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult SafetyMessagesForDateDialog(DateTime? date, Guid? teamId)
        {
            if (date.HasValue && teamId.HasValue)
            {
                SafetyMessagesViewModel safetyMessages = Services.SafetyMessageService
                                                                    .GetSafetyMessagesByDateAndTeam(date.Value, teamId.Value);

                return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessagesForDateDialog.cshtml", safetyMessages);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [Authorize(Roles = iHandoverRoles.RelayGroups.Admins)]
        public ActionResult SafetyMessagePreviewDialog(Guid safetyMessageId)
        {
            if (safetyMessageId != Guid.Empty)
            {
                SafetyMessageViewModel safetyMessage = Services.SafetyMessageService.GetSafetyMessageForPreview(safetyMessageId);

                return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessagePreviewDialog.cshtml", safetyMessage);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpPost]
        public ActionResult SetSafetyMessageShowForUser(Guid safetyMessageId)
        {
            if (safetyMessageId != Guid.Empty)
            {
                Guid userId = (Guid)Membership.GetUser().ProviderUserKey;
                Services.SafetyMessageService.SetSafetyMessageShowForUser(userId, safetyMessageId);
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpGet]
        public ActionResult GetSafetyMessagesForUser(string date)
        {
            DateTime safetyDate;
            Guid userId = (Guid)Membership.GetUser().ProviderUserKey;

            if(DateTime.TryParse(date, out safetyDate))
            {
                IEnumerable<SafetyMessageViewModel> model = Services.SafetyMessageService.GetSafetyMessageForUser(userId, safetyDate);

                return PartialView("~/Views/Safety/v1/ScheduleMessage/_SafetyMessageDialog.cshtml", model);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

    }

}

Relay.Web/Views/Safety/v1/MajorHazard/CreateMajorHazard.cshtml
@model EditMajorHazardViewModel

@*

    safety ver 1

*@

@using (Html.BeginForm("AddMajorHazard", "MajorHazard", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div Id="form" class="upload-photo large-margin">
        <div data-provides="fileinput" class="fileinput fileinput-new">
            <div data-trigger="fileinput" class="fileinput-preview thumbnail"></div>
            <div>
                <span class="btn-file">
                    @Html.TextBoxFor(m => m.Icon, new { @class = "new-icon", type = "file", accept = "image/*", })
                    @Html.ValidationMessageFor(Model => Model.Icon)
                </span>
            </div>
        </div>
    </div>
    @Html.TextBoxFor(Model => Model.Name, new { @class = "tx-input", placeholder = "Enter title" })
    @Html.ValidationMessageFor(Model => Model.Name)
}

Relay.Web/Views/Safety/v1/MajorHazard/MajorHazardList.cshtml
@model IPagedList<MajorHazardViewModel>

@*

    safety ver 1

*@

@{
    Layout = "~/Views/Shared/Layouts/Main/Authorized_Layout.cshtml";
}
<div class="administration-content">
    <div Id="majorHazardPanel">
        <div class="safely-content row">
            <div class="majhazard grey first col-lg-2 col-md-3 col-sm-6 col-xs-6">Major Hazards</div>
            @foreach (var majorHazard in Model)
            {
                <div class="majhazard orange col-lg-2 col-md-3 col-sm-6 col-xs-6" major-hazard-Id="@majorHazard.Id">
                    <img src="@Url.Action("GetImage", "Media", new { imageId = majorHazard.IconId, width = 95, height = 95 })">
                    <div class="tx">@majorHazard.Name</div>
                </div>
            }
            <div class="majhazard orange col-lg-2 col-md-3 col-sm-6 col-xs-6" Id="newForm">
                <div Id='newItem' class='plus'></div>
            </div>
        </div>
        <div class="pagination-block">
            <div class="pagination-pages">
                @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount).Options(o => o
                    .DisplayTemplate("BootstrapPagination")
                    .MaxNrOfPages(1)
                    .DisplayFirstAndLastPage())
            </div>
        </div>
    </div>
</div>

<script src="~/Content/js/relay/safety/v1/dialogs/major-hazard-dialog-v1.module.js"></script>
<script src="~/Content/js/relay/safety/v1/major-hazard-v1.module.js"></script>

Relay.Web/Views/Safety/v1/MajorHazard/_EditMajorHazardDialog.cshtml
@model IEnumerable<CriticalControlViewModel>

<div Id="editMajorHazardDialog" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static" class="modal fade major-hazard-dialog">

    <div class="modal-dialog">
        <div class="theme">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="row vertical-center">
                        <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6">
                            <div Id="modalTitle" class="modal-title">Edit Major Hazard</div>
                        </div>
                        <div class="col col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
                            <button type="submit" class="btn btn-save">Save</button>
                            <button type="button" data-dismiss="modal" aria-hidden="true" class="btn btn-close"></button>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding">
                            <div Id="majorHazardEditSwiper">
                                <div class="table-thead row">
                                    <div class="col col-lg-5 col-md-5 col-sm-5 col-xs-5 title">Critical Controls</div>
                                    <div class="col col-lg-7 col-md-7 col-sm-7 col-xs-7 title">Team Permissions</div>
                                </div>
                                <div class="critical-controls-table">
                                    <div class="swiper-prev"></div>
                                    <div class="swiper-next"></div>
                                    <div class="swiper-container critical-control-swiper">
                                        <div class="swiper-wrapper">
                                            @if (Model.Any())
                                            {
                                                foreach (var criticalControl in Model)
                                                {
                                                    <div class="row swiper-slide critical-control-item">
                                                        <div class="col col-lg-5 col-md-5 col-sm-5 col-xs-5 critical-control-name overflow">
                                                            <p critical-control-Id="@criticalControl.Id" class="overflow">@criticalControl.Name</p>
                                                        </div>
                                                        <div class="col col-lg-7 col-md-7 col-sm-7 col-xs-7 critical-control-permission">
                                                            @foreach (var team in criticalControl.Teams)
                                                            {
                                                                <div class="team-fill">@team.Text</div>
                                                            }
                                                        </div>
                                                    </div>
                                                }
                                            }
                                            else
                                            {
                                                <div class="no-critical-controls">No critical controls</div>
                                            }
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <div Id="form-input-safely" class="btn-plus-white center-block add-new">
                                        <div class="span"></div>
                                    </div>
                                </div>
                            </div>
                            <div Id="new-safely-popup-safely"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>