Relay.Web/Controllers/Settings/AdministrationController.cs
using System;
using System.Web.Mvc;
using MomentumPlus.Relay.Interfaces;
using MomentumPlus.Relay.Models;
using System.Collections.Generic;
using System.Net;
using System.Web;
using MomentumPlus.Relay.Roles;
using Microsoft.AspNet.Identity;

namespace MomentumPlus.Relay.Web.Controllers
{
    [Authorize(Roles = iHandoverRoles.Relay.Administrator + "," + iHandoverRoles.Relay.iHandoverAdmin + "," + iHandoverRoles.Relay.ExecutiveUser)]
    public class AdministrationController : BaseController
    {
        //IOC
        public AdministrationController(IServicesUnitOfWork servicesUnitOfWork) : base(servicesUnitOfWork)
        { }


        [HttpGet]
        public ActionResult DetailsTab()
        {

            var model = Services.AdministrationService.PopulateAccountDetailsViewModel();

            return PartialView("~/Views/Settings/Administration/Tabs/_DetailsTab.cshtml", model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DetailsTab(AccountDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.AdministrationService.UpdateAccountDetails(model);
                return Content("ok");
            }

            return PartialView("~/Views/Settings/Administration/Tabs/_DetailsTab.cshtml", model);
        }


        [HttpGet]
        [Authorize(Roles = iHandoverRoles.Relay.iHandoverAdmin)]
        public ActionResult VersionDetailsTab()
        {
            var model = Services.AdministrationService.PopulateVersionDetailsViewModel();

            return PartialView("~/Views/Settings/Administration/Tabs/_VersionDetailsTab.cshtml", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VersionDetailsTab(VersionDetailsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.AdministrationService.UpdateVersionDetails(model);
                return Content("ok");
            }

            return PartialView("~/Views/Settings/Administration/Tabs/_VersionDetailsTab.cshtml", model);
        }


        [HttpGet]
        public ActionResult ThirdPartyTab()
        {
            var model = Services.AdministrationService.PopulateThirdPartySettingsViewModel();

            return PartialView("~/Views/Settings/Administration/Tabs/_ThirdPartyTab.cshtml", model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThirdPartyTab(ThirdPartySettingsViewModel model)
        {
            if (ModelState.IsValid)
            {
                Services.AdministrationService.UpdateThirdPartySettings(model);
                return Content("ok");
            }

            return PartialView("~/Views/Settings/Administration/Tabs/_ThirdPartyTab.cshtml", model);
        }


        [HttpGet]
        public ActionResult PreferencesTab()
        {
            Guid userId = Guid.Parse(User.Identity.GetUserId());

            var model = Services.AdministrationService.PopulatePreferencesSettingsViewModel(userId);

            return PartialView("~/Views/Settings/Administration/Tabs/_PreferencesTab.cshtml", model);
        }


        [HttpGet]
        public ActionResult UsersTab()
        {
            IEnumerable<UserDetailsViewModel> model = Services.UserService.GetUsersDetails();
            return PartialView("~/Views/Settings/Administration/Tabs/_UsersTab.cshtml", model);
        }

        [HttpPost]
        public ActionResult RemoveUser(Guid userId)
        {
            Guid initiatorId = Guid.Parse(User.Identity.GetUserId());

            if (Services.AuthService.RemoveUser(userId, initiatorId))
            {
                Services.UserService.RemoveUser(userId);

                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [HttpGet]
        public ActionResult UpgradeTab()
        {
            return PartialView("~/Views/Settings/Administration/Tabs/_UpgradeTab.cshtml");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PreferencesTab(PreferencesSettingsViewModel model, HttpPostedFileBase logoImage)
        {

            if (ModelState.IsValid)
            {
                Services.AdministrationService.UpdatePreferencesSettings(model, logoImage);
                return Content("ok");
            }

            return PartialView("~/Views/Settings/Administration/Tabs/_PreferencesTab.cshtml", model);
        }

        [HttpPost]
        public ActionResult ReactivateUser(Guid userId, bool status, int usersCount)
        {
            if (!status)
            {
                Services.RestrictionService.UsersLimitExceededForDeactivateUsers(userId, iHandoverRoles.Relay.User, usersCount);
            }

            Services.UserService.ReactivateUser(userId, status);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
    }
}

Relay.Web/Views/Settings/Administration/Tabs/_DetailsTab.cshtml
@model AccountDetailsViewModel

<div style="display: block;" class="tab-pane active" Id="administrationDetails">
  @using (Html.BeginForm("DetailsTab", "Administration", FormMethod.Post))
  {
  @Html.AntiForgeryToken()
    <div class="row">
        <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
            <div class="row">
                <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                    <div class="field-container">
                        <span class="title-select">@Html.LabelFor(model => model.VersionDetails)</span>
              @Html.TextBoxFor(model => model.VersionDetails, new {@class = "simple-input", @readonly = "readonly"})
                    </div>
                </div>
                <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                    <div class="field-container">
                        <span class="title-select">@Html.LabelFor(model => model.PurchaseDate)</span>
              @Html.TextBoxFor(model => model.PurchaseDate, new {@class = "simple-input", @readonly = "readonly"})
                    </div>
                </div>
                <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                    <div class="field-container">
                        @if (@Model.isMultiTenant)
                        {
                            <span class="title-select">Next Billing Date</span>
                        }
                        else
                        {
                            <span class="title-select">@Html.LabelFor(model => model.LicenceEndDate)</span>
                        }

              @Html.TextBoxFor(model => model.LicenceEndDate, new {@class = "simple-input", @readonly = "readonly"})
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
            <div class="row">
                <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                    <div class="field-container">
                        <span class="title-select">@Html.LabelFor(model => model.PlanType)</span>
              @Html.TextBoxFor(model => model.PlanType, new {@class = "simple-input", @readonly = "readonly"})
                    </div>
                </div>
                @if (!string.IsNullOrEmpty(@Model.TechnicalSupport))
                {
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.TechnicalSupport)</span>
                @Html.TextBoxFor(model => model.TechnicalSupport, new {@class = "simple-input", @readonly = "readonly"})
                        </div>
                    </div>
                }
                <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                    <div class="row">
                        <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                            <div class="field-container">
                                <span class="title-select">@Html.LabelFor(model => model.Templates)</span>
                  @Html.TextBoxFor(model => model.Templates, new {@class = "simple-input", @readonly = "readonly"})
                            </div>
                        </div>
                        <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                            <div class="field-container">
                                <span class="title-select">@Html.LabelFor(model => model.Handovers)</span>
                  @Html.TextBoxFor(model => model.Handovers, new {@class = "simple-input", @readonly = "readonly"})
                            </div>
                        </div>
                    </div>
                </div>
          @if (Model.AutoRenewSubscription.HasValue)
          {
            <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
              <div class="radio-btn-group">
                @Html.LabelFor(m => m.AutoRenewSubscription, new {@class = "title-select"})
                <label>
                  @Html.RadioButtonFor(m => m.AutoRenewSubscription, true)
                  <span class="radio-label">On</span>
                </label>
                <label>
                  @Html.RadioButtonFor(m => m.AutoRenewSubscription, false)
                  <span class="radio-label">Off</span>
                </label>
            </div>
        </div>
          }
    </div>
      </div>
    </div>
    <script>
      $('input[name="AutoRenewSubscription"]').bind("change", function ()
      {
        $("#settingsDialog button[type=submit]").trigger("activate");
      });
    </script>
  }
</div>

Relay.Web/Views/Settings/Administration/Tabs/_PreferencesTab.cshtml
@model PreferencesSettingsViewModel

<div style="display: block;" class="tab-pane" Id="administrationPreferences">
    @using (Html.BeginForm("PreferencesTab", "Administration", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col col-lg-8 col-sm-8 col-md-8 col-xs-8">
                <div class="row">
                    <div class="col col-lg-7 col-sm-7 col-md-7 col-xs-7">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.HandoverTriggerType)</span>
                            @Html.EnumDropDownListFor(model => model.HandoverTriggerType, new { @class = "select-list" })
                            @Html.ValidationMessageFor(m => m.HandoverTriggerType)
                        </div>
                    </div>
                    <div class="col col-lg-5 col-sm-5 col-md-5 col-xs-5">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.HandoverTriggerTime)</span>
                            @Html.DropDownListFor(model => model.HandoverTriggerTime,
                                Enumerable.Range(00, 24).Select(i =>
                                    new SelectListItem
                                    {
                                        Value = DateTime.Today.Subtract(-TimeSpan.FromHours(i)).ToString("hh:mmtt").ToLower(),
                                        Text = DateTime.Today.Subtract(-TimeSpan.FromHours(i)).ToString("hh:mmtt").ToLower()
                                    }), null, new { @class = "select-list" })
                        </div>
                    </div>
                </div>
                <div class="row margin-top-20">
                    <div class="col col-lg-7 col-sm-7 col-md-7 col-xs-7">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.HandoverPreviewType)</span>
                            @Html.EnumDropDownListFor(model => model.HandoverPreviewType, new {@class = "select-list"})
                            @Html.ValidationMessageFor(m => m.HandoverPreviewType)
                        </div>
                    </div>
                    <div class="col col-lg-5 col-sm-5 col-md-5 col-xs-5">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.HandoverPreviewTime)</span>
                            @Html.DropDownListFor(model => model.HandoverPreviewTime,
                                Enumerable.Range(00, 24).Select(i =>
                                    new SelectListItem
                                    {
                                        Value = DateTime.Today.Subtract(-TimeSpan.FromHours(i)).ToString("hh:mmtt").ToLower(),
                                        Text = DateTime.Today.Subtract(-TimeSpan.FromHours(i)).ToString("hh:mmtt").ToLower()
                                    }), "never", new {@class = "select-list"})
                        </div>
                    </div>
                </div>
                <div class="row margin-top-20">
                    @*<div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.Timezone)</span>
                            @Html.DropDownListFor(model => model.Timezone,
                                TimeZoneInfo.GetSystemTimeZones().Select(zone =>
                                    new SelectListItem
                                    {
                                        Value = zone.Id,
                                        Text = zone.DisplayName.Substring(0, zone.DisplayName.IndexOf(" ", StringComparison.Ordinal)) + " " + TZNames.GetNamesForTimeZone(zone.Id, "en-GB").Generic
                                    }).OrderByDescending(zone => zone.Text), null, new { @class = "select-list" })
                        </div>
                    </div>*@
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="select-type">
                            <span class="title-select">@Html.LabelFor(m => m.Timezone)</span>
                            @Html.DropDownListFor(model => model.Timezone,
                                TimeZoneInfo.GetSystemTimeZones().Select(zone =>
                                    new SelectListItem
                                    {
                                        Value = zone.Id,
                                        Text = zone.DisplayName
                                    }).OrderBy(zone => zone.Text), null, new { @class = "select-list" })
                        </div>
                    </div>
                </div>
                <div class="row margin-top-20">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="tags-input-container">
                            <label class="tags-input-title">Allowed File Types</label>
                            <div class="ms-ctn form-control ms-ctn-focus tags-input"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-lg-4 col-sm-4 col-md-4 col-xs-4">
                <div class="row text-center">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">

                        <div class="upload-photo margin-top-20" style="height: 100px;">
                            <div data-provides="fileinput" class="fileinput fileinput-new">
                                <div data-trigger="fileinput" class="fileinput-preview thumbnail">
                                    @if (!Model.LogoImageId.HasValue)
                                    {
                                        <img src="~/Content/img/no-image.png" class="media-object img-circle assigned-to-large-photo avatar-image" />
                                    }
                                    else
                                    {
                                        <img src="/Media/GetImage?imageId=@(Model.LogoImageId)&width=90&height=90&@(Guid.NewGuid())"
                                             class="media-object img-circle assigned-to-large-photo avatar-image">
                                    }
                                </div>
                                <div>
                                    <span class="btn btn-default btn-file">
                                        <input Id="logoImage" name="logoImage" type="file" accept="image/*" />
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 edit-photo">
                        <div style="cursor: pointer;" onclick="javascript: $('#logoImage').click()">
                            <span class="glyphicon glyphicon glyphicon-upload edit-photo" aria-hidden="true"></span>
                            <span>choose company logo</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script>

            var tagsInput = $('#administrationPreferences .tags-input').magicSuggest({
                maxSelection: 100,
                placeholder: 'Type some file types',
                hideTrigger: true,
                allowDuplicates: false,
                allowFreeEntries: true,
                toggleOnClick: true,
                name: "AllowedFileTypes",
                value: [ @Html.Raw(Model.AllowedFileTypesString)]
            });
        </script>

    }
</div>

Relay.Web/Views/Settings/Administration/Tabs/_ThirdPartyTab.cshtml
@model ThirdPartySettingsViewModel


<div style="display: block;" class="tab-pane" Id="administrationThirdParty">
    @using (Html.BeginForm("ThirdPartyTab", "Administration", FormMethod.Post))
    {
        @Html.AntiForgeryToken()


        <div class="row">
            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.TwilioAccount)</span>
                            @Html.TextBoxFor(model => model.TwilioAccount, new { @class = "simple-input", @placeholder = Html.DisplayNameFor(n => n.TwilioAccount) })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.TwilioEndPoint)</span>
                            @Html.TextBoxFor(model => model.TwilioEndPoint, new { @class = "simple-input", @placeholder = Html.DisplayNameFor(n => n.TwilioEndPoint) })
                            @Html.ValidationMessageFor(m => m.TwilioEndPoint)
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.TwilioPhoneNumber)</span>
                            @Html.TextBoxFor(model => model.TwilioPhoneNumber, new { @class = "simple-input", type = "phone", @placeholder = Html.DisplayNameFor(n => n.TwilioPhoneNumber) })
                            @Html.ValidationMessageFor(model => model.TwilioPhoneNumber)
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.SMSGateway)</span>
                            @Html.TextBoxFor(model => model.SMSGateway, new { @class = "simple-input", @placeholder = Html.DisplayNameFor(n => n.SMSGateway) })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.SMSPerUserPerDay)</span>
                            @Html.TextBoxFor(model => model.SMSPerUserPerDay, new { @class = "simple-input number-input", @min = "1", @max = "200", @type = "number", @placeholder= "SMS quantity" })
                            @Html.ValidationMessageFor(model => model.SMSPerUserPerDay)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Relay.Web/Views/Settings/Administration/Tabs/_UpgradeTab.cshtml
<div style="display: block;" class="tab-pane" Id="administrationUpgrade">
    <div class="row">
        <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 text-center">
            <h4 class="upgrade-text" style="padding: 50px;font-weight: 700;font-size: 16px;">Coming Soon</h4>
        </div>
    </div>
</div>

Relay.Web/Views/Settings/Administration/Tabs/_VersionDetailsTab.cshtml
@model VersionDetailsViewModel

<div style="display: block;" class="tab-pane active" Id="administrationVersionDetails">
    @using (Html.BeginForm("VersionDetailsTab", "Administration", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.LicenceEndDate)</span>
                            @{ Html.EnableClientValidation(false); }
                            @Html.TextBox("LicenceEndDate", Model.LicenceEndDate.CalendarFormatWidthYear(), new { @class = "simple-input datepicker", @placeholder = Html.DisplayNameFor(n => n.LicenceEndDate) })
                            @Html.ValidationMessageFor(m => m.LicenceEndDate)
                            @{ Html.EnableClientValidation(true); }
                        </div>
                    </div>
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.iHandoverAccountManager)</span>
                            @Html.TextBoxFor(model => model.iHandoverAccountManager, new { @class = "simple-input", @placeholder = Html.DisplayNameFor(n => n.iHandoverAccountManager) })
                        </div>
                    </div>
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="row">
                            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                                <div class="field-container">
                                    <span class="title-select">@Html.LabelFor(model => model.MaximumTemplates)</span>
                                    @Html.TextBoxFor(model => model.MaximumTemplates, new { @class = "simple-input number-input", @min = "1", @max = "100", @type = "number", @placeholder = "Max Templates" })
                                    @Html.ValidationMessageFor(model => model.MaximumTemplates)
                                </div>
                            </div>
                            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                                <div class="field-container">
                                    <span class="title-select">@Html.LabelFor(model => model.MaximumHandovers)</span>
                                    @Html.TextBoxFor(model => model.MaximumHandovers, new { @class = "simple-input number-input", @min = "1", @max = "200", @type = "number", @placeholder = "Max Handovers" })
                                    @Html.ValidationMessageFor(model => model.MaximumHandovers)
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-lg-6 col-sm-6 col-md-6 col-xs-6">
                <div class="row">
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.DomainUrl)</span>
                            @Html.TextBoxFor(model => model.DomainUrl, new { @class = "simple-input", @readonly = "readonly" })
                        </div>
                    </div>
                    <div class="col col-lg-12 col-sm-12 col-md-12 col-xs-12 margin-top-20">
                        <div class="field-container">
                            <span class="title-select">@Html.LabelFor(model => model.HostingProvider)</span>
                            @Html.TextBoxFor(model => model.HostingProvider, new { @class = "simple-input", @readonly = "readonly" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            $('.datepicker').datepicker({
                format: "dd M yyyy",
                todayBtn: "linked",
                container: "#settingsDialog",
                todayHighlight: true
            }).on('changeDate', function ()
            {
                $(this).datepicker('hide');
            });
        </script>
  }
</div>